audit_header: false
title: "Dallas - Fort Worth's Best Real Estate Training"
description: Brian and Tisha White, a top Real Estate Agent in Dallas - Fort Worth, shares their own internal real estate agent training for free. Their Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Free Newsletter
    url: /subscribe/
  - title: Join Our Team
    url: /join-our-team/    

client:
  name: Brian and Tisha White
  title:
  license_number:
  about_markdown: |
    Founded in 2014, we are built around making your Real Estate Career AWESOME!

    BlueFuse was started by Tisha and Brian White to build a family business, serve our community and keep Brian closer to our 3 amazing boys. Brian spent 20 years in Fortune 50 companies leading teams, providing exceptional customer service and negotiating with some of the toughest businesses in the world. Tisha is simply brilliant in all things Real Estate. She has photographic recall of floor plans, builders and design. Plus, she’s an incredible connector.

    Why are we called BLUEFUSE?

    We’re BLUE because we’re blessed with those Amazing Boys and it’s our family’s favorite color! FUSE means to join or blend. We FUSED our skills to provide YOU an EXCEPTIONAL Real Estate Career Experience.

    Now, we’re a growing team with outstanding, caring agents and staff, focused on building client Wealth and building Careers Worth Having for our Agents and Friends.

    At BlueFuse, we help YOU build and Amazing Real Estate Business. Isn’t That a Bright Idea?
  brand: BlueFuse Group
  brokerage: eXp Realty
  market: Dallas - Fort Worth
  address: 2300 Highland Village Rd Suite 120<br>Highland Village, TX 75077
  phone: 817-752-9126
  phone_type:
  phone2:
  phone2_type:
  email: brian@bluefuserealty.com
  email2: tisha@bluefuserealty.com
  url: https://findhomesindfwmetroplex.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how BlueFuse Group can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BlueFuseRealty/
  linkedin_url: https://www.linkedin.com/in/bluefuserealty/
  youtube_url:
  twitter_url: https://twitter.com/bluefuserealty
  instagram_url: https://www.instagram.com/bluefuserealty/
  pinterest_url: https://www.pinterest.com/bluefuserealty/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/dallas-fort-worth-real-estate-podcast-brian-tisha-white/id1455148660?mt=2

podcast:
  title: 'Dallas - Fort Worth Recruiting Podcast with Brian and Tisha White'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more in Dallas - Fort Worth Area Real Estate Market'
  description: 'If you are Looking to build your real estate career, get all the information and the latest updates then lets talk about how BlueFuse Group can take your business to new heights.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Dallas - Fort Worth, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Brian and Tisha White'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Dallas - Fort Worth Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2769e5'
  theme_color: '#123b4f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
